"""
SAP Toolkit 配置模块
"""

from .config import (
    API_KEY, BASE_URL, MODEL, MODEL_PRO,
    THINKING_ENABLED, THINKING_BUDGET_TOKENS, get_thinking_config
)
from .prompts import (
    PDF_TO_MARKDOWN_PROMPT,
    PDF_TO_MARKDOWN_MULTI_PROMPT,
    IS_TOC_PAGE_PROMPT,
    QA_SYSTEM_PROMPT,
    PRIMARY_SYSTEM_PROMPT,
    PRIMARY_EXTRACTION_RULES,
    SECONDARY_SYSTEM_PROMPT,
    SECONDARY_EXTRACTION_RULES,
    SAFETY_SYSTEM_PROMPT,
    SAFETY_EXTRACTION_RULES,
    SAMPLE_SYSTEM_PROMPT,
    SAMPLE_EXTRACTION_RULES,
    STAT_METHODS_SYSTEM_PROMPT,
    STAT_METHODS_EXTRACTION_RULES,
)
from .rules import (
    METHOD_NAME_MAPPING,
    normalize_method_name,
    classify_table_type,
    EXTRACTION_TASKS,
)
from .api_logger import APILogger

__all__ = [
    # config
    "API_KEY", "BASE_URL", "MODEL", "MODEL_PRO",
    "THINKING_ENABLED", "THINKING_BUDGET_TOKENS", "get_thinking_config",
    # prompts
    "PDF_TO_MARKDOWN_PROMPT", "PDF_TO_MARKDOWN_MULTI_PROMPT",
    "IS_TOC_PAGE_PROMPT", "QA_SYSTEM_PROMPT",
    "PRIMARY_SYSTEM_PROMPT", "PRIMARY_EXTRACTION_RULES",
    "SECONDARY_SYSTEM_PROMPT", "SECONDARY_EXTRACTION_RULES",
    "SAFETY_SYSTEM_PROMPT", "SAFETY_EXTRACTION_RULES",
    "SAMPLE_SYSTEM_PROMPT", "SAMPLE_EXTRACTION_RULES",
    "STAT_METHODS_SYSTEM_PROMPT", "STAT_METHODS_EXTRACTION_RULES",
    # rules
    "METHOD_NAME_MAPPING", "normalize_method_name", "classify_table_type", "EXTRACTION_TASKS",
    # logger
    "APILogger",
]
